theme = "dark_plus"

# Editor settings (https://docs.helix-editor.com/configuration.html)
[editor]
line-number = "relative"
cursorline = true
auto-save = true
shell = ["C:\\Program Files\\Git\\bin\\bash.exe", "-c"]
completion-replace = true
true-color = true
rulers = [81]
color-modes = true

[editor.statusline]
left = [
  "spacer",
  "version-control",
  "spacer",
  "mode",
  "spinner",
  "file-name"
]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]

[editor.cursor-shape]
insert = "bar"
select = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

# Key mappings (https://docs.helix-editor.com/remapping.html)
[keys.normal]
C-c = ["keep_primary_selection", "collapse_selection"]
"C-/" = ["toggle_comments", "select_mode"]

[keys.normal.space]
c = ":config-open"
u = ":reset-diff-change"
H = ":toggle file-picker.hidden"

[keys.insert]
C-c = "normal_mode"
C-h = "move_char_left"
C-l = "move_char_right"

[keys.select]
C-c = ["normal_mode", "keep_primary_selection", "collapse_selection"]
"C-/" = ["toggle_comments", "select_mode"]
