theme = "tokyonight"

# Editor settings (https://docs.helix-editor.com/configuration.html)
[editor]
line-number = "relative"
cursorline = true
auto-save = true
shell = ["C:\\Program Files\\Git\\bin\\bash.exe", "-c"]
idle-timeout = 1
completion-trigger-len = 1
completion-replace = true
true-color = true
bufferline = "multiple"
rulers = [81]
color-modes = true

[editor.statusline]
left = [
  "spacer",
  "version-control",
  "spacer",
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

# [editor.whitespace.render]
# space = "all"
# nbsp = "all"
# tab = "all"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "·"
# tabpad = "·"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

# Key mappings (https://docs.helix-editor.com/remapping.html)
[keys.normal]
C-c = ["keep_primary_selection", "collapse_selection"]
"C-[" = ["keep_primary_selection", "collapse_selection"]
"C-/" = ["toggle_comments", "select_mode"]
C-S = ":write"

[keys.normal.space]
c = ":config-open"
u = ":reset-diff-change"
H = [
":toggle file-picker.hidden",
":toggle file-picker.ignore",
":toggle file-picker.git-ignore"
]
A = ":toggle lsp.auto-signature-help"
W = ":write"
# Erdtree config (https://github.com/solidiquis/erdtree)
t = ":sh erd -IH"
T = ":sh erd -.iIHL 2"
# Linux tree config (backup)
# t = ":sh tree -RL 2"
# T = ":sh tree -aRL 2"

[keys.insert]
C-c = "normal_mode"
"C-[" = "normal_mode"
C-h = "move_char_left"
C-l = "move_char_right"
C-S = ":write"

[keys.select]
C-c = ["normal_mode", "keep_primary_selection", "collapse_selection"]
"C-[" = "normal_mode"
"C-/" = ["toggle_comments", "select_mode"]
C-S = ":write"
