[[language]]
name = "rust"

[[language]]
name = "html"
formatter = { command = 'prettier.cmd', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier.cmd', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier.cmd', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier.cmd', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier.cmd', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier.cmd', args = ["--parser", "typescript"] }
auto-format = true

# From the Helix GitHub wiki
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" } }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = { typeCheckingMode = "strict" }
